# Generated by Django 5.1.2 on 2024-10-24 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("careerbridge_app1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="enrollment_data",
            new_name="enrollment_date",
        ),
    ]
